/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeniRouteImport } from './routes/meni'
import { Route as NarackiRouteImport } from './routes/naracki'
import { Route as RezervaciiRouteImport } from './routes/rezervacii'
import { Route as KategorijaIdRouteImport } from './routes/kategorija.$id'
import { Route as RasporedIndexRouteImport } from './routes/raspored.index'
import { Route as RasporedIdRouteImport } from './routes/raspored.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeniRoute = MeniRouteImport.update({
  id: '/meni',
  path: '/meni',
  getParentRoute: () => rootRouteImport,
} as any)
const NarackiRoute = NarackiRouteImport.update({
  id: '/naracki',
  path: '/naracki',
  getParentRoute: () => rootRouteImport,
} as any)
const RezervaciiRoute = RezervaciiRouteImport.update({
  id: '/rezervacii',
  path: '/rezervacii',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorijaIdRoute = KategorijaIdRouteImport.update({
  id: '/kategorija/$id',
  path: '/kategorija/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RasporedIndexRoute = RasporedIndexRouteImport.update({
  id: '/raspored/',
  path: '/raspored/',
  getParentRoute: () => rootRouteImport,
} as any)
const RasporedIdRoute = RasporedIdRouteImport.update({
  id: '/raspored/$id',
  path: '/raspored/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meni': typeof MeniRoute
  '/naracki': typeof NarackiRoute
  '/rezervacii': typeof RezervaciiRoute
  '/kategorija/$id': typeof KategorijaIdRoute
  '/raspored/$id': typeof RasporedIdRoute
  '/raspored/': typeof RasporedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meni': typeof MeniRoute
  '/naracki': typeof NarackiRoute
  '/rezervacii': typeof RezervaciiRoute
  '/kategorija/$id': typeof KategorijaIdRoute
  '/raspored/$id': typeof RasporedIdRoute
  '/raspored': typeof RasporedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meni': typeof MeniRoute
  '/naracki': typeof NarackiRoute
  '/rezervacii': typeof RezervaciiRoute
  '/kategorija/$id': typeof KategorijaIdRoute
  '/raspored/$id': typeof RasporedIdRoute
  '/raspored/': typeof RasporedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meni'
    | '/naracki'
    | '/rezervacii'
    | '/kategorija/$id'
    | '/raspored/$id'
    | '/raspored/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meni'
    | '/naracki'
    | '/rezervacii'
    | '/kategorija/$id'
    | '/raspored/$id'
    | '/raspored'
  id:
    | '__root__'
    | '/'
    | '/meni'
    | '/naracki'
    | '/rezervacii'
    | '/kategorija/$id'
    | '/raspored/$id'
    | '/raspored/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeniRoute: typeof MeniRoute
  NarackiRoute: typeof NarackiRoute
  RezervaciiRoute: typeof RezervaciiRoute
  KategorijaIdRoute: typeof KategorijaIdRoute
  RasporedIdRoute: typeof RasporedIdRoute
  RasporedIndexRoute: typeof RasporedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meni': {
      id: '/meni'
      path: '/meni'
      fullPath: '/meni'
      preLoaderRoute: typeof MeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naracki': {
      id: '/naracki'
      path: '/naracki'
      fullPath: '/naracki'
      preLoaderRoute: typeof NarackiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezervacii': {
      id: '/rezervacii'
      path: '/rezervacii'
      fullPath: '/rezervacii'
      preLoaderRoute: typeof RezervaciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorija/$id': {
      id: '/kategorija/$id'
      path: '/kategorija/$id'
      fullPath: '/kategorija/$id'
      preLoaderRoute: typeof KategorijaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raspored/': {
      id: '/raspored/'
      path: '/raspored'
      fullPath: '/raspored/'
      preLoaderRoute: typeof RasporedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raspored/$id': {
      id: '/raspored/$id'
      path: '/raspored/$id'
      fullPath: '/raspored/$id'
      preLoaderRoute: typeof RasporedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeniRoute: MeniRoute,
  NarackiRoute: NarackiRoute,
  RezervaciiRoute: RezervaciiRoute,
  KategorijaIdRoute: KategorijaIdRoute,
  RasporedIdRoute: RasporedIdRoute,
  RasporedIndexRoute: RasporedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
